name: Test arm32v7 container
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

env:
  LANG: en_US.UTF-8
  LANGUAGE: en_US:en
  LC_ALL: en_US.UTF-8
  FORCE_UNSAFE_CONFIGURE: 1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REG_TOKEN: ${{ secrets.REG_TOKEN }}
  SCREENSCRAPER_DEV_LOGIN: ${{ secrets.SCREENSCRAPER_DEV_LOGIN }}
  GAMESDB_APIKEY: ${{ secrets.GAMESDB_APIKEY }}
  CHEEVOS_DEV_LOGIN: ${{ secrets.CHEEVOS_DEV_LOGIN }}
  HFS_DEV_LOGIN: ${{ secrets.HFS_DEV_LOGIN }}

jobs:
  build:
    name: Build REG-Linux for CHA
    runs-on: ubuntu-latest
    steps:
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: raspios_lite:latest
        cpu_info: raspberrypi_3b
        commands: |
            uname -a
            echo "grep Model /proc/cpuinfo:"
            grep Model /proc/cpuinfo
