name: Test arm32v7 container
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: TEST
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/arm/v7
      - name: TEST
        run: |
          uname -a
          echo "grep Model /proc/cpuinfo:"
          grep Model /proc/cpuinfo
